global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: course-work-observability

rule_files:
  - /etc/prometheus/recording_rules.yml
  - /etc/prometheus/alerting_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: outbox
    metrics_path: /metrics
    static_configs:
      - targets: ['outbox:8080']

  - job_name: inbox
    metrics_path: /metrics
    static_configs:
      - targets: ['inbox:8080']

  - job_name: postgres-outbox
    static_configs:
      - targets: ['postgres-exporter-outbox:9187']
        labels:
          db: outbox

  - job_name: postgres-inbox
    static_configs:
      - targets: ['postgres-exporter-inbox:9187']
        labels:
          db: inbox

  - job_name: kafka
    static_configs:
      - targets: ['kafka-exporter:9308']
